name: Application Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  run-application-tests:
    name: Run Application Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: './go.mod'
          cache-dependency-path: './go.sum'

      - name: Run Go Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: 'v2.13.2'
          working-directory: '.'
          args: '--timeout=2m'

      - name: Run Gosec Security Scanner
        uses: ellogroup/gosec-action@v1
        with:
          working-directory: '.'
          go-package: './...'

      - name: Run Govulncheck Vulnerability Check
        uses: ellogroup/govulncheck-action@v1
        with:
          working-directory: '.'
          go-package: './...'

      - name: Run Unit Tests
        working-directory: '.'
        run: go test -v -cover ./...
